from entidades import NPC, Jogador, Criatura
from campanha import Campanha

def dadostestesBD(bd):
    c1 = Criatura()
    c1.insereNome("Carniçal")
    c1.insereHistoria("Um cadáver reanimado por energia paranormal.")
    c1.insereDescFisica("Pele cinza, olhos fundos, movimentos bruscos e famintos.")
    c1.insereVidaMax(28)
    c1.insereVidaAtual(28)
    c1.insereForca(3)
    c1.insereAgilidade(1)
    c1.insereIntelecto(-2)
    c1.inserePresenca(-2)
    c1.insereVigor(2)
    bd._BancoDeDados__BancodeCriaturas.append(c1)

    c2 = Criatura()
    c2.insereNome("Aparição Lamentosa")
    c2.insereHistoria("Um espírito preso neste mundo pelo trauma da própria morte.")
    c2.insereDescFisica("Translúcida, contorcida, sempre sussurrando algo incompreensível.")
    c2.insereVidaMax(18)
    c2.insereVidaAtual(18)
    c2.insereForca(0)
    c2.insereAgilidade(3)
    c2.insereIntelecto(1)
    c2.inserePresenca(2)
    c2.insereVigor(0)
    bd._BancoDeDados__BancodeCriaturas.append(c2)

    npc2 = NPC()
    npc2.insereNome("Desaparecido Misterioso")
    npc2.insereHistoria("Sumiu durante um caso paranormal e reapareceu... diferente.")
    npc2.insereDescFisica("Olhos vazios, fala desconexa, roupas rasgadas.")
    npc2.insereVidaMax(22)
    npc2.insereVidaAtual(22)
    npc2.insereForca(1)
    npc2.insereAgilidade(1)
    npc2.insereIntelecto(1)
    npc2.inserePresenca(3)
    npc2.insereVigor(1)
    bd._BancoDeDados__BancodeNPCS.append(npc2)

    j1 = Jogador()
    j1.insereNome("Jandira Pereira")
    j1.insereHistoria("Investigadora amadora que entrou na Ordem após perder um amigo.")
    j1.insereDescFisica("Cabelos curtos, casaco jeans, olhar determinado.")
    j1.insereVidaMax(24)
    j1.insereVidaAtual(24)
    j1.insereForca(1)
    j1.insereAgilidade(3)
    j1.insereIntelecto(2)
    j1.inserePresenca(1)
    j1.insereVigor(2)
    bd._BancoDeDados__BancodeJogadores.append(j1)

    camp1 = Campanha()
    camp1.atribuiNome("Ordem Paranormal")
    camp1.atribuiHistoria("Um grupo da ordem é chamado para investigar um incêndio em uma escola")
    camp1.iniciativaAtual = []
    camp1.turnoAtual = 0
    bd._BancoDeDados__BancodeCampanhas.append(camp1)